### ISSUE TITLE
Add configuration option for minimum age

### ISSUE THREAD

**Issue by mrmeyers99** [whitesource/merge-confidence#1648]
Not sure this is the right place to put this request, but I'd really like to be able to only get PRs for packages that are X days old.  I've seen many times where I get a PR for a new boto3 version, but when my CI tests run it can't find that version yet.  If I could put an age requirement on it, then I could avoid that situation. It seems like right now the Age only shows up on the badge, but you can't include it in the configuration options.

**Comment by rarkins** [comment]
This is the wrong repo. You should look up the docs for stabilityDays
