### ISSUE TITLE
Ability to disable merge confidence reporting for private repos.

### ISSUE THREAD

**Issue by Renari** [whitesource/merge-confidence#1649]
There should be a way to disable merge confidence for specific repos so that internal project names are not leaked to [https://badges.renovateapi.com](https://badges.renovateapi.com)

**Comment by rarkins** [comment]
The preset in this repo is just regular Renovate config: https://github.com/whitesource/merge-confidence/blob/main/beta.json

So you could take this config and embed it inside a package rule with your own match or exclude patterns.
