### ISSUE TITLE
which kind of data is collected/analyzed (gdpr)

### ISSUE THREAD

**Issue by strowi** [whitesource/merge-confidence#18]
Hi,

i found whitesource's general [privacy policy](https://www.whitesourcesoftware.com/privacy-policy/), but it would be useful for transparency and other reasons to clarify which kind of data is collected/transmitted etc..

(btw the privacy policy link on https://resources.whitesourcesoftware.com/news-whitesource/merge-confidence-feature# links back to the page itself)

regards,
strowi

**Comment by rarkins** [comment]
The WhiteSource Renovate App does not store personal data. Data for Merge Confidence is associated per-repository but importantly is anyway data necessary for Renovate to operate (dependency list, branch status, etc).

The Privacy Policy for the app can be found here: https://www.whitesourcesoftware.com/free-developer-tools/terms-of-use#renovate. I'll ask the web team to fix up the broken link you found at the bottom of the merge confidence post.

**Comment by strowi** [comment]
Thx for the explanation;)

**Comment by rarkins** [comment]
The privacy policy link at the bottom of https://resources.whitesourcesoftware.com/news-whitesource/merge-confidence-feature is now updated (note: it points to the privacy policy of the *website*, not Renovate specifically, but I think that's correct).
