### ISSUE TITLE
Setup automation for merge-confidence "roadmap" project board

### ISSUE THREAD

**Issue by HonkingGoose** [whitesource/merge-confidence#21]
Issue #11 and #12 were manually closed, but the project board still lists them as "To do", instead of moving the cards to "Done".
I think this is because there is no automation setup on the project board.

See https://docs.github.com/en/github/managing-your-work-on-github/configuring-automation-for-project-boards

**Comment by 76090** [comment]
Michelle.robinson8062@gmail.com is the Work by github.com.  if you were to choose to offer any advice.

**Comment by HonkingGoose** [comment]
I don't think see any open project boards on this repository anymore. I'm closing this issue as not planned.
