### ISSUE TITLE
Error type: Cannot find preset's package (github>whitesource/merge-confidence:beta)

### ISSUE THREAD

**Issue by memoricab** [whitesource/merge-confidence#22]
Trying to use it self-hosted renovate. We are getting above error. 

Thank you for your help.

**Comment by rarkins** [comment]
Is your Renovate instance able to reach `github.com`? And if so, have you configured a github.com access token so that you don't get rate limited?

**Comment by memoricab** [comment]
Hi rarkins,

Thank for reply.

Yes Renovate instance is able to reach github.com and we have an access token.

**Comment by rarkins** [comment]
Unfortunately there's nothing I can do to help with the information provided.

**Comment by memoricab** [comment]
yeah I see, I will investigate more to find  some logs.

Thank you.
