### ISSUE TITLE
Action Required: Fix Renovate Configuration

### ISSUE THREAD

**Issue by infodi** [whitesource/merge-confidence#24]
There is an error with this repository's Renovate configuration that needs to be fixed. As a precaution, Renovate will stop PRs until it is resolved.

Error type: Cannot find preset's package (github>whitesource/merge-confidence:beta)

How to use?  --> "extends": ["github>whitesource/merge-confidence:beta"], adding on renovate.json we get this error above.

**Comment by rarkins** [comment]
I'm assuming you are running self-hosted. For some reason your Renovate bot is unable to fetch from github.com. Is it blocked or forced through a proxy? Did you configure `GITHUB_COM_TOKEN`?

It's trying to fetch this file: https://github.com/whitesource/merge-confidence/blob/main/beta.json

So you could copy that into your own config or presets as an alternative, but ideally you should work out why it can't fetch from github.com as other things may also fail.

**Comment by infodi** [comment]
Rarkins, thanks.
Adding the beta.json config to our renovate.json it helped.
There's some way to only enable automerge for high confidence for example.

here our packageRules:

  "packageRules": [
    {
      "datasources": ["maven", "npm", "pypi"],
      "updateTypes": ["patch", "minor", "major"],
      "prBodyColumns": ["Package", "Change", "Age", "Adoption", "Passing", "Confidence"]
    },
    {
      "paths": ["project/service/**/*"],
      "groupName": "Java Service",
      "groupSlug": "java",
      "labels": ["dependencies", "renovate", "service"],
      "updateTypes": ["minor"],
      "automerge": true,
      "automergeType": "pr",
      "reviewers": ["team:services-member"],
      "assignees": ["Member"],
      "assignAutomerge": true
    }
  ]

**Comment by rarkins** [comment]
> There's some way to only enable automerge for high confidence for example.

This is not yet supported
