### ISSUE TITLE
Force pushing of the PR creates CI issues

### ISSUE THREAD

**Issue by silverbucket** [whitesource/merge-confidence#25]
I just tried out WhiteSource Renovate today. So far, all of the PRs are causing failures during CI testing. 

```
$ git fetch origin +refs/pull/364/merge:
fatal: couldn't find remote ref refs/pull/364/merge
```

```
$ git checkout -qf f2bb2ca98968b82ce4700d7e33c3500870444543
fatal: reference is not a tree: f2bb2ca98968b82ce4700d7e33c3500870444543
The command "git checkout -qf f2bb2ca98968b82ce4700d7e33c3500870444543" failed and exited with 128 during .
```

Seems it has something to do with the fact that every PR created by this app force-pushes and there's some race condition happening between the PR and the CI.

**Comment by rarkins** [comment]
Hi, this is not related to merge confidence so in the wrong repo. Please start a new discussion in https://github.com/renovatebot/renovate/discussions but you'll need to provide more details than the above. Renovate does employ force pushing of its own branches when it needs to update them, so if your systems can't support that then unfortunately they won't be compatible.

**Comment by silverbucket** [comment]
The system is github + travis-ci, pretty standard isn't it? I'll re-open the issue there.

**Comment by rarkins** [comment]
Yes, and there's 200k + installed repositories on GitHub and nobody's raised it before
