### ISSUE TITLE
suggestion: fill in the the about section of the repository landing page

### ISSUE THREAD

**Issue by HonkingGoose** [whitesource/merge-confidence#7]
I think it would be good to fill in the **About** section with a nice description of the repository, and add some relevant tags.

See the **About** section that is on the Renovate bot repository (right side of picture):

![fill_in_about_section](https://user-images.githubusercontent.com/34918129/100018222-6d9d1c00-2ddc-11eb-8356-d1677fb9d8c7.png)

**Comment by rarkins** [comment]
Done, thanks
