### ISSUE TITLE
Is Merge Confidence going to replace `stabilityDays`?

### ISSUE THREAD

**Issue by HonkingGoose** [whitesource/merge-confidence#8]
I know that `stabilityDays` has some edge cases, where it's not always functioning well.

I was thinking that Merge Confidence, is also a more useful concept, as it gives more feedback and information on the proposed upgrade. So it might make sense to scrap `stabilityDays` in favor of a `mergeConfidence` feature where you can select a preferred stability level.

So the question is what is the direction you're going to take this? Is Merge Confidence a straight up replacement of `stabilityDays` or are you keeping both things around?

**Comment by rarkins** [comment]
I think we'll keep both. Main reason being that Merge Confidence won't be an algorithm that you can personally tweak, yet some people may prefer to have different stability days, e.g. some will say 3 is fine, others want a week, others want more. I hope that for most that Merge Confidence is reliable enough that they don't need to configure stability days though.
